{% set version = "1.7" %}

package:
  name: verboselogs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/v/verboselogs/verboselogs-{{ version }}.tar.gz
  sha256: e33ddedcdfdafcb3a174701150430b11b46ceb64c2a9a26198c76a156568e427

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - verboselogs

about:
  home: https://verboselogs.readthedocs.io
  license: MIT
  license_file: LICENSE.txt
  summary: "Verbose logging level for Python's logging module."

extra:
  recipe-maintainers:
    - ocefpaf
