{% set version = "1.4" %}

package:
  name: verboselogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/verboselogs/verboselogs-{{ version }}.tar.gz
  sha256: 1a3b30956f6a1b8eeb69c9a57b4be96665469be49d4931096f2ece415206c357

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - verboselogs

about:
  home: https://verboselogs.readthedocs.io
  license: MIT
  summary: "Verbose logging level for Python's logging module."

extra:
  recipe-maintainers:
    - ocefpaf
