travis:
  secure:
    BINSTAR_TOKEN: WorbXaFjFPd5E5xAoSLSKuCOVGQ1BzDgmR8a4YJOTkjcOFTZ5FTa+0OSzW38r5tpJT82YxIZZZe4tJKeqzKbNNf46uXizsc/8YahnKDRqyYGK2g30xxq9MqZhvRG0Xwp/o5YegQp/rcAMNNPxwUKIxdlWbFwfJmXgbmVXfJt3F/DD3V641C9+JN1q04ui1AYMSYBVBI7MWWunj+GmOL2ta94V73oY841CB7bj1SzMKmOdXv6Eodg/FvjYBR8VPaQqt+5rjaDEG5QggnAt3h1yCVo+QcmLq28BgQ+A/kqavOJTw6LxHfQUTVf8ckg9M5bjEHYRio47M2BumgxOZ/+Tf/nmK+s94JAZYuKLYvFSyWWUMtxSNvzT1EyzU3nXsfvOb40qyGbe0pEBiR35FkqaT3FiF85stcfQCLeZLQqK5MC2goXODKp2FtX8KKg2SZ912vptvkk5asbuHV+5861zQjXkAL+zJ0aH9lUqsbNcvYQx7V2FSxfBbXNxdIavEoktDVzD3EgeIz4+dUeWjSluvX1hoEDjojGaTROPVA2pH+0F+DwdoBNrgrf88qbq7hXzUGhpeL5seUG0iTfAP629CRvIh7yKaVBAcDAQDBnstSVfz0iwLvxmgqzj5sq1cvTYORmRrtBTPS11im7/xUPifjjNhw/QVHer8LfO6FGcxw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
