travis:
  secure:
    BINSTAR_TOKEN: FLo+BEXY1EDNZJh8bU373cOPgOIwUT5Lk5WU4t0VrsQkZ6feEeFE5laao06pMLYFUztGbZ2z5barmNrJM+/kIomtC4Q+igL1/Yl6wFKaHFlC8vF1GE+4+GJMUhQNh0KEiYDy5tCRi6AWfqDi5015xHvipSTJsVZ/3qoCm/Mzi/oxF3+D7osD7ym/ZVoVkPBYKUc7oIvEl5GOBvLZTkw5T0dFNtCM7xp/BV5+Z0ZHlN53vVXVpUriCG1s0WHBroU6lJHJjzNcwchHrn6wJytXQPD4vMmQxm7jyd5Z6TPrzFdAyewbE2bZQBwx+dxL8R7SNeOcoQ4BB7wW6XAUMT1Lmh6WsouVOIqxLXE9cN52flNz4LfUsKwEkyPd71DhYp11Nygd+/KQ+kiHkJq5zE90vWzNh3RGc6EA6MvWUiu9Bgjr/xPJgkCZm2ZXPwHlwYXWWKfQKtlAKDCzbIWHR9LC8nRh+iE1gHzjJgqYkFf/5n0GKihOVrvHqTbB0uwRvay/wq5KJhix0mRDM+BgDGKl+f4tirhcM7c8jVLRobGdatyS3AmaAWUh843qH9VdpoFagkX3XV00P98jvf+bnVrPYuMhQI2u17yfq/cPV0Q1YzUkUmVsPnTuAW1Cn42cLTyics9vXPxMPHq8XYrGZJ+vvsAJBupBE7Mk5zbIqGBJOqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
